name: androtell
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  camera: ^0.11.0+1
  percent_indicator: ^4.2.2
  intl: ^0.19.0
  path_provider: ^2.1.3
  shared_preferences: ^2.0.18
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.0
  flutter: 
    sdk: flutter


dev_dependencies: 
  get: ^4.6.6
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/bg_splash.png
    - assets/splash_logo.png
    - assets/bg_beranda.png
    - assets/logo_beranda.png
    - assets/barcode.png
    - assets/button_scan.png
    - lib/icon/
  uses-material-design: true

